apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240502051520.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240502051520.0.0+build.6aff574
  releaseNotes: |
    Release v20240502051520.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-01-05-2024-22-23-03-890742723/where-for-dinner-search-my-apps-bundle@sha256:b0f08c50f4f7469564efaddf4ab5e2647e3e6d3c95f919cd7c17d37aee968e53
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

