apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240502051549.0.0+build.6aff574
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240502051549.0.0+build.6aff574
  releaseNotes: |
    Release v20240502051549.0.0+build.6aff574 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-01-05-2024-22-23-03-890742723/where-for-dinner-notify-my-apps-bundle@sha256:435214fdfffb88234f03c1ed507ae792e7686886edc468901c30c1bbfd17e666
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

